name: Java CI with Maven
 
on:
  push:
    branches: ["main"] 
    types: [closed]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
 
    - name: Render Deploy Action
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ https://api.render.com/deploy/srv-crr15256l47c73cbbh5g?key=3r9jedJCIeM }}
        api-key: ${{ rnd_CG835U7D6CABKmnL2TGdwo5yEzcZ }}
